### ISSUE TITLE
Broken Documentation link

### ISSUE THREAD

**Issue by kauefontes** [jaimevp54/htmlBuilder#4]
Hi, Bro! 

The documentation link that is in description is broken! =D

**Comment by jaimevp54** [comment]
Better late than never, I guess! 😆 I've made a couple of updates recently, along with updating the documentation link. Feel free to take a look, and thanks a lot for pointing this out.

**Comment by kauefontes** [comment]
Thank you very much, bro! Better late than never! hahaha

Nice lib, btw =D
