### ISSUE TITLE
Syntax Error in tags.py

### ISSUE THREAD

**Issue by akshay-dandekar** [jaimevp54/htmlBuilder#5]
Traceback (most recent call last):
  File "python_html_builder.py", line 2, in <module>
    from htmlBuilder.tags import *
  File "/home/abc/.local/lib/python2.7/site-packages/htmlBuilder/tags.py", line 20
    belongs_to: list = None
              ^
SyntaxError: invalid syntax

**Comment by AgarwalPragy** [comment]
What version of Python are you using? The `:list` thingy is a type annotation, and works only with python 3.5+

**Comment by kauefontes** [comment]
Oh, i'm using Python 2.7. Certainly this is the cause of the error.

Thank you

**Comment by AgarwalPragy** [comment]
Note that type annotations don't do anything (unless you use them specifically, which this library does not).

So, you can simply edit the files `tags.py` and `attributes.py` and change `variable: annotation = something` to simply `variable = something`. That should make it work for Python 2.7
